# Generated by Django 4.0 on 2022-01-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=20, null=True)),
                ('grade', models.CharField(choices=[('M1', '중1'), ('M2', '중2'), ('M3', '중3'), ('H1', '고1'), ('H2', '고2'), ('H3', '고3'), ('E4', '초4'), ('E5', '초5'), ('E6', '초6')], max_length=5)),
                ('phone_number', models.CharField(max_length=10)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
