# Generated by Django 4.0 on 2022-01-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('M1', '중1'), ('M2', '중2'), ('M3', '중3'), ('H1', '고1'), ('H2', '고2'), ('H3', '고3'), ('E4', '초4'), ('E5', '초5'), ('E6', '초6')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
