# Generated by Django 4.0 on 2022-01-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(choices=[('Korean', '국어'), ('Math', '수학'), ('English', '영어'), ('Science', '과학'), ('Social', '사회')], max_length=20),
        ),
    ]
